In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
!pip install scikit-learn==1.2.0
import sklearn
sklearn.__version__

Requirement already satisfied: scikit-learn==1.2.0 in c:\users\owner\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\owner\anaconda3\lib\site-packages (from scikit-learn==1.2.0) (2.2.0)
Requirement already satisfied: scipy>=1.3.2 in c:\users\owner\anaconda3\lib\site-packages (from scikit-learn==1.2.0) (1.9.1)
Requirement already satisfied: numpy>=1.17.3 in c:\users\owner\anaconda3\lib\site-packages (from scikit-learn==1.2.0) (1.21.5)
Requirement already satisfied: joblib>=1.1.1 in c:\users\owner\anaconda3\lib\site-packages (from scikit-learn==1.2.0) (1.2.0)

'1.2.0'

In [3]:
top= pd.read_csv(r'C:\Users\owner\Desktop\topics.csv\topics.csv')
cor= pd.read_csv(r'C:\Users\owner\Desktop\correlations.csv\correlations.csv')
con= pd.read_csv(r'C:\Users\owner\Desktop\content.csv\content.csv')
sub= pd.read_csv(r'C:\Users\owner\Desktop\sample_submission.csv')
corr= pd.read_csv(r'C:\Users\owner\Desktop\correlations.csv\correlations.csv')

In [4]:
cor.isnull().sum()

topic_id       0
content_ids    0
dtype: int64

In [5]:
cor['content_ids']=cor['content_ids'].str.split()
cor=cor.explode('content_ids')
cor

             topic_id     content_ids
0      t_00004da3a1b2  c_1108dd0c7a5d
0      t_00004da3a1b2  c_376c5a8eb028
0      t_00004da3a1b2  c_5bc0e1e2cba0
0      t_00004da3a1b2  c_76231f9d0b5e
1      t_00068291e9a4  c_639ea2ef9c95
...               ...             ...
61513  t_fff9e5407d13  c_d64037a72376
61514  t_fffbe1d5d43c  c_46f852a49c08
61514  t_fffbe1d5d43c  c_6659207b25d5
61515  t_fffe14f1be1e  c_cece166bad6a
61516  t_fffe811a6da9  c_92b8fad372ee

[279919 rows x 2 columns]

In [6]:
cor.isnull().sum()

topic_id       0
content_ids    0
dtype: int64

In [7]:
cor1=cor.groupby('content_ids').count()
cor1.rename(columns={'topic_id':'num_of_topics'}, inplace=True)
cor1.head(2)

                num_of_topics
content_ids
c_00002381196d              5
c_000087304a9e              2

In [8]:
cor1.sort_values('num_of_topics', ascending= False, inplace=True)
cor1.head(3)

                num_of_topics
content_ids
c_dd739e116435            241
c_2f8849826d71             75
c_4f5925b37bdf             54

In [9]:
cor2=cor.groupby('topic_id').count()
cor2.rename(columns={'content_ids':'num_of_contents'}, inplace= True)
cor2.head()

                num_of_contents
topic_id
t_00004da3a1b2                4
t_00068291e9a4                4
t_00069b63a70a                1
t_0006d41a73a8                5
t_0008768bdee6                3

In [10]:
con1=pd.merge(cor1,con, left_on='content_ids', right_on='id',how='inner')
con1.rename(columns={'id':'content_ids'}, inplace=True)
con1.set_index('content_ids', inplace=True)
con1.head(3)

,num_of_topics,title,description,kind,text,language,copyright_holder,license
content_ids,,,,,,,,
c_dd739e116435,241,বই,NaN,document,NaN,bn,NaN,NaN
c_2f8849826d71,75,InfoPage,NaN,html5,This open text is disseminated via the Open Ed...,en,CSU and Merlot,CC BY-NC-SA
c_4f5925b37bdf,54,Index,NaN,html5,NaN,en,NaN,NaN

In [11]:
con1.shape

(154047, 8)

In [12]:
cor.head(2)

         topic_id     content_ids
0  t_00004da3a1b2  c_1108dd0c7a5d
0  t_00004da3a1b2  c_376c5a8eb028

In [13]:
corr.head(2)

         topic_id                                        content_ids
0  t_00004da3a1b2  c_1108dd0c7a5d c_376c5a8eb028 c_5bc0e1e2cba0 c...
1  t_00068291e9a4  c_639ea2ef9c95 c_89ce9367be10 c_ac1672cdcd2c c...

In [14]:
top.head(2)

,id,title,description,channel,category,level,language,parent,has_content
0,t_00004da3a1b2,Откриването на резисторите,"Изследване на материали, които предизвикват на...",000cf7,source,4,bg,t_16e29365b50d,True
1,t_000095e03056,Unit 3.3 Enlargements and Similarities,NaN,b3f329,aligned,2,en,t_aa32fb6252dc,False

In [15]:
top1=pd.merge(top, corr, left_on='id', right_on='topic_id', how='inner')
top1.drop(columns='id',inplace=True)
top1.head(2)

,title,description,channel,category,level,language,parent,has_content,topic_id,content_ids
0,Откриването на резисторите,"Изследване на материали, които предизвикват на...",000cf7,source,4,bg,t_16e29365b50d,True,t_00004da3a1b2,c_1108dd0c7a5d c_376c5a8eb028 c_5bc0e1e2cba0 c...
1,Entradas e saídas de uma função,Entenda um pouco mais sobre funções.,8e286a,source,4,pt,t_d14b6c2a2b70,True,t_00068291e9a4,c_639ea2ef9c95 c_89ce9367be10 c_ac1672cdcd2c c...

In [16]:
top2=pd.merge(top1, cor2, on='topic_id', how='inner')
top2.head(2)

,title,description,channel,category,level,language,parent,has_content,topic_id,content_ids,num_of_contents
0,Откриването на резисторите,"Изследване на материали, които предизвикват на...",000cf7,source,4,bg,t_16e29365b50d,True,t_00004da3a1b2,c_1108dd0c7a5d c_376c5a8eb028 c_5bc0e1e2cba0 c...,4
1,Entradas e saídas de uma função,Entenda um pouco mais sobre funções.,8e286a,source,4,pt,t_d14b6c2a2b70,True,t_00068291e9a4,c_639ea2ef9c95 c_89ce9367be10 c_ac1672cdcd2c c...,4

In [17]:
top2['content_ids']=top2['content_ids'].str.split()
top3=top2.explode('content_ids')
top3.reset_index()
top3.head(2)

,title,description,channel,category,level,language,parent,has_content,topic_id,content_ids,num_of_contents
0,Откриването на резисторите,"Изследване на материали, които предизвикват на...",000cf7,source,4,bg,t_16e29365b50d,True,t_00004da3a1b2,c_1108dd0c7a5d,4
0,Откриването на резисторите,"Изследване на материали, които предизвикват на...",000cf7,source,4,bg,t_16e29365b50d,True,t_00004da3a1b2,c_376c5a8eb028,4

In [18]:
top3['has_content'].value_counts()

True    279919
Name: has_content, dtype: int64

In [19]:
data=pd.merge(con1,top3, on='content_ids', how='inner')

In [20]:
data.head(2)

,content_ids,num_of_topics,title_x,description_x,kind,text,language_x,copyright_holder,license,title_y,description_y,channel,category,level,language_y,parent,has_content,topic_id,num_of_contents
0,c_dd739e116435,241,বই,NaN,document,NaN,bn,NaN,NaN,নিজে করি,NaN,36068f,aligned,4,bn,t_7dcd717461b4,True,t_02a7923ac3f1,3
1,c_dd739e116435,241,বই,NaN,document,NaN,bn,NaN,NaN,ভগ্নাংশের যোগ,NaN,00a2b4,aligned,4,bn,t_f839311577c0,True,t_02bcfa7b72ec,4

In [21]:
data.drop(['title_x',
           'description_x',
           'text',
           'copyright_holder',
           'license','title_y',
           'description_y', 
           'language_y'],axis=1, inplace=True)

In [22]:
print('channel =', data['channel'].value_counts().count())
print('kind =', data['kind'].value_counts().count())
print('category =', data['category'].value_counts().count())
print('level =', data['level'].value_counts().count())
print('parent =', data['parent'].value_counts().count())
print('topic_id =', data['topic_id'].value_counts().count())
print('language_x =', data['language_x'].value_counts().count())

channel = 171
kind = 5
category = 3
level = 11
parent = 14757
topic_id = 61517
language_x = 27

In [23]:
data.isnull().sum()

content_ids         0
num_of_topics       0
kind                0
language_x          0
channel             0
category            0
level               0
parent             26
has_content         0
topic_id            0
num_of_contents     0
dtype: int64

In [24]:
data.head(10)

,content_ids,num_of_topics,kind,language_x,channel,category,level,parent,has_content,topic_id,num_of_contents
0,c_dd739e116435,241,document,bn,36068f,aligned,4,t_7dcd717461b4,True,t_02a7923ac3f1,3
1,c_dd739e116435,241,document,bn,00a2b4,aligned,4,t_f839311577c0,True,t_02bcfa7b72ec,4
2,c_dd739e116435,241,document,bn,36068f,aligned,4,t_2eba9502dafd,True,t_03005404b28a,1
3,c_dd739e116435,241,document,bn,00a2b4,aligned,4,t_5ac1eaab74a1,True,t_03ea6cb9a100,1
4,c_dd739e116435,241,document,bn,00a2b4,aligned,4,t_0215674c661d,True,t_04df4fee08b4,1
5,c_dd739e116435,241,document,bn,00a2b4,aligned,4,t_2290d2361430,True,t_05f4612484e7,5
6,c_dd739e116435,241,document,bn,00a2b4,aligned,4,t_6683959d96f7,True,t_070136c72382,1
7,c_dd739e116435,241,document,bn,36068f,aligned,4,t_d37ddd6a80dc,True,t_07438ba9aec9,1
8,c_dd739e116435,241,document,bn,00a2b4,aligned,4,t_578d188b6d8e,True,t_0b888d5f773b,2
9,c_dd739e116435,241,document,bn,00a2b4,aligned,4,t_3bd75c3be1d1,True,t_0bf1603ca8df,1

In [25]:
sub.head()

         topic_id                                        content_ids
0  t_00004da3a1b2  c_1108dd0c7a5d c_376c5a8eb028 c_5bc0e1e2cba0 c...
1  t_00068291e9a4  c_639ea2ef9c95 c_89ce9367be10 c_ac1672cdcd2c c...
2  t_00069b63a70a                                     c_11a1dc0bfb99
3  t_0006d41a73a8  c_0c6473c3480d c_1c57a1316568 c_5e375cf14c47 c...
4  t_4054df11a74e                      c_3695c5dc1df6 c_f2d184a98231

In [26]:
final_test1=cor[cor['content_ids'].map(lambda id: "c_11a1dc0bfb99" in 'content_ids')]
final_test1

Empty DataFrame
Columns: [topic_id, content_ids]
Index: []

In [27]:
final_test1=cor[cor['topic_id'].map(lambda id: "t_00004da3a1b2" in 'topic_id')]
final_test1

Empty DataFrame
Columns: [topic_id, content_ids]
Index: []

In [28]:
final_test1=data[data['topic_id'].map(lambda id: "t_00004da3a1b2" in id )] 
final_test2=data[data['topic_id'].map(lambda id: "t_00068291e9a4" in id )]
final_test3=data[data['topic_id'].map(lambda id: "t_00069b63a70a" in id )]
final_test4=data[data['topic_id'].map(lambda id: "t_0006d41a73a8" in id )]
final_test5=data[data['topic_id'].map(lambda id: "t_4054df11a74e" in id )]

In [29]:
final_test= pd.concat([final_test1,final_test2,final_test3,
                       final_test4, final_test5])
final_test

,content_ids,num_of_topics,kind,language_x,channel,category,level,parent,has_content,topic_id,num_of_contents
128745,c_5bc0e1e2cba0,2,video,bg,000cf7,source,4,t_16e29365b50d,True,t_00004da3a1b2,4
168973,c_376c5a8eb028,2,video,bg,000cf7,source,4,t_16e29365b50d,True,t_00004da3a1b2,4
170319,c_1108dd0c7a5d,2,video,bg,000cf7,source,4,t_16e29365b50d,True,t_00004da3a1b2,4
234940,c_76231f9d0b5e,1,video,bg,000cf7,source,4,t_16e29365b50d,True,t_00004da3a1b2,4
97725,c_89ce9367be10,3,video,pt,8e286a,source,4,t_d14b6c2a2b70,True,t_00068291e9a4,4
100422,c_ebb7fdf10a7e,3,exercise,pt,8e286a,source,4,t_d14b6c2a2b70,True,t_00068291e9a4,4
105318,c_639ea2ef9c95,3,exercise,pt,8e286a,source,4,t_d14b6c2a2b70,True,t_00068291e9a4,4
119430,c_ac1672cdcd2c,3,video,pt,8e286a,source,4,t_d14b6c2a2b70,True,t_00068291e9a4,4
216340,c_11a1dc0bfb99,1,document,en,6e3ba4,source,3,t_4054df11a74e,True,t_00069b63a70a,1
67865,c_b972646631cb,5,video,bg,000cf7,source,4,t_e2452e21d252,True,t_0006d41a73a8,5
104214,c_5e375cf14c47,3,video,bg,000cf7,source,4,t_e2452e21d252,True,t_0006d41a73a8,5
116790,c_1c57a1316568,3,video,bg,000cf7,source,4,t_e2452e21d252,True,t_0006d41a73a8,5
117630,c_0c6473c3480d,3,video,bg,000cf7,source,4,t_e2452e21d252,True,t_0006d41a73a8,5
121977,c_d7a0d7eaf799,3,video,bg,000cf7,source,4,t_e2452e21d252,True,t_0006d41a73a8,5
201254,c_f2d184a98231,1,video,es,6e3ba4,source,2,t_acbbd893e6af,True,t_4054df11a74e,2
233677,c_3695c5dc1df6,1,html5,en,6e3ba4,source,2,t_acbbd893e6af,True,t_4054df11a74e,2

In [30]:
final_test.reset_index()
final_test.head(5)

,content_ids,num_of_topics,kind,language_x,channel,category,level,parent,has_content,topic_id,num_of_contents
128745,c_5bc0e1e2cba0,2,video,bg,000cf7,source,4,t_16e29365b50d,True,t_00004da3a1b2,4
168973,c_376c5a8eb028,2,video,bg,000cf7,source,4,t_16e29365b50d,True,t_00004da3a1b2,4
170319,c_1108dd0c7a5d,2,video,bg,000cf7,source,4,t_16e29365b50d,True,t_00004da3a1b2,4
234940,c_76231f9d0b5e,1,video,bg,000cf7,source,4,t_16e29365b50d,True,t_00004da3a1b2,4
97725,c_89ce9367be10,3,video,pt,8e286a,source,4,t_d14b6c2a2b70,True,t_00068291e9a4,4

In [31]:
data.drop([128745, 168973, 170319, 234940, 97725, 100422, 105318, 
           119430, 216340, 67865, 104214, 116790, 117630, 121977, 
           201254, 233677], axis=0, inplace=True)

In [32]:
data.head(1)

,content_ids,num_of_topics,kind,language_x,channel,category,level,parent,has_content,topic_id,num_of_contents
0,c_dd739e116435,241,document,bn,36068f,aligned,4,t_7dcd717461b4,True,t_02a7923ac3f1,3

In [33]:
data.drop(['num_of_topics', 'num_of_contents'], axis=1, inplace= True)
data.head(2)

,content_ids,kind,language_x,channel,category,level,parent,has_content,topic_id
0,c_dd739e116435,document,bn,36068f,aligned,4,t_7dcd717461b4,True,t_02a7923ac3f1
1,c_dd739e116435,document,bn,00a2b4,aligned,4,t_f839311577c0,True,t_02bcfa7b72ec

In [34]:
data.set_index(data['topic_id'], drop=True, inplace=True)
data.head(2)

,content_ids,kind,language_x,channel,category,level,parent,has_content,topic_id
topic_id,,,,,,,,,
t_02a7923ac3f1,c_dd739e116435,document,bn,36068f,aligned,4,t_7dcd717461b4,True,t_02a7923ac3f1
t_02bcfa7b72ec,c_dd739e116435,document,bn,00a2b4,aligned,4,t_f839311577c0,True,t_02bcfa7b72ec

In [35]:
data.shape

(279903, 9)

In [36]:
print('channel =', data['channel'].value_counts().count())
print('kind =', data['kind'].value_counts().count())
print('category =', data['category'].value_counts().count())
print('level =', data['level'].value_counts().count())
print('parent =', data['parent'].value_counts().count())
print('topic_id =', data['topic_id'].value_counts().count())
print('language_x =', data['language_x'].value_counts().count())
print('content_ids =', data['content_ids'].value_counts().count())

channel = 171
kind = 5
category = 3
level = 11
parent = 14757
topic_id = 61512
language_x = 27
content_ids = 154043

In [37]:
x_raw= data.drop(['content_ids', 'topic_id', 'parent', 'has_content'], axis='columns',)
x_raw

                    kind language_x channel      category  level
topic_id
t_02a7923ac3f1  document         bn  36068f       aligned      4
t_02bcfa7b72ec  document         bn  00a2b4       aligned      4
t_03005404b28a  document         bn  36068f       aligned      4
t_03ea6cb9a100  document         bn  00a2b4       aligned      4
t_04df4fee08b4  document         bn  00a2b4       aligned      4
...                  ...        ...     ...           ...    ...
t_a1dfd9838010  document         es  6e90a7       aligned      6
t_79501d4f3204  document         en  9202e6        source      1
t_2266e8e007f9     html5         en  88c9d6  supplemental      4
t_3f979326b3f2     video         mr  217993        source      4
t_6f81cfdcadcc     video         en  ef2088  supplemental      5

[279903 rows x 5 columns]

In [38]:
y_raw=data.drop(['kind', 'channel', 'category', 'level', 'parent', 
             'has_content', 'topic_id', 'language_x'], axis=1)
y_raw

                   content_ids
topic_id
t_02a7923ac3f1  c_dd739e116435
t_02bcfa7b72ec  c_dd739e116435
t_03005404b28a  c_dd739e116435
t_03ea6cb9a100  c_dd739e116435
t_04df4fee08b4  c_dd739e116435
...                        ...
t_a1dfd9838010  c_86d6beba86ad
t_79501d4f3204  c_2ef6fab4aa8e
t_2266e8e007f9  c_2ef77f82ec07
t_3f979326b3f2  c_86d59d8b8a82
t_6f81cfdcadcc  c_ffffe5254266

[279903 rows x 1 columns]

In [39]:
y_raw['content_ids'].value_counts().count()

154043

In [40]:
final_test.head(2)

,content_ids,num_of_topics,kind,language_x,channel,category,level,parent,has_content,topic_id,num_of_contents
128745,c_5bc0e1e2cba0,2,video,bg,000cf7,source,4,t_16e29365b50d,True,t_00004da3a1b2,4
168973,c_376c5a8eb028,2,video,bg,000cf7,source,4,t_16e29365b50d,True,t_00004da3a1b2,4

In [41]:
final_test.drop(['num_of_topics', 'num_of_contents', 'has_content'], axis=1, inplace= True)
final_test.set_index(final_test['topic_id'], drop=True, inplace=True)
final_test

,content_ids,kind,language_x,channel,category,level,parent,topic_id
topic_id,,,,,,,,
t_00004da3a1b2,c_5bc0e1e2cba0,video,bg,000cf7,source,4,t_16e29365b50d,t_00004da3a1b2
t_00004da3a1b2,c_376c5a8eb028,video,bg,000cf7,source,4,t_16e29365b50d,t_00004da3a1b2
t_00004da3a1b2,c_1108dd0c7a5d,video,bg,000cf7,source,4,t_16e29365b50d,t_00004da3a1b2
t_00004da3a1b2,c_76231f9d0b5e,video,bg,000cf7,source,4,t_16e29365b50d,t_00004da3a1b2
t_00068291e9a4,c_89ce9367be10,video,pt,8e286a,source,4,t_d14b6c2a2b70,t_00068291e9a4
t_00068291e9a4,c_ebb7fdf10a7e,exercise,pt,8e286a,source,4,t_d14b6c2a2b70,t_00068291e9a4
t_00068291e9a4,c_639ea2ef9c95,exercise,pt,8e286a,source,4,t_d14b6c2a2b70,t_00068291e9a4
t_00068291e9a4,c_ac1672cdcd2c,video,pt,8e286a,source,4,t_d14b6c2a2b70,t_00068291e9a4
t_00069b63a70a,c_11a1dc0bfb99,document,en,6e3ba4,source,3,t_4054df11a74e,t_00069b63a70a
t_0006d41a73a8,c_b972646631cb,video,bg,000cf7,source,4,t_e2452e21d252,t_0006d41a73a8
t_0006d41a73a8,c_5e375cf14c47,video,bg,000cf7,source,4,t_e2452e21d252,t_0006d41a73a8
t_0006d41a73a8,c_1c57a1316568,video,bg,000cf7,source,4,t_e2452e21d252,t_0006d41a73a8
t_0006d41a73a8,c_0c6473c3480d,video,bg,000cf7,source,4,t_e2452e21d252,t_0006d41a73a8
t_0006d41a73a8,c_d7a0d7eaf799,video,bg,000cf7,source,4,t_e2452e21d252,t_0006d41a73a8
t_4054df11a74e,c_f2d184a98231,video,es,6e3ba4,source,2,t_acbbd893e6af,t_4054df11a74e
t_4054df11a74e,c_3695c5dc1df6,html5,en,6e3ba4,source,2,t_acbbd893e6af,t_4054df11a74e

In [70]:
finalX=final_test.drop(['content_ids', 'parent', 'topic_id'], axis=1,)
finalX

                    kind language_x channel category  level
topic_id
t_00004da3a1b2     video         bg  000cf7   source      4
t_00004da3a1b2     video         bg  000cf7   source      4
t_00004da3a1b2     video         bg  000cf7   source      4
t_00004da3a1b2     video         bg  000cf7   source      4
t_00068291e9a4     video         pt  8e286a   source      4
t_00068291e9a4  exercise         pt  8e286a   source      4
t_00068291e9a4  exercise         pt  8e286a   source      4
t_00068291e9a4     video         pt  8e286a   source      4
t_00069b63a70a  document         en  6e3ba4   source      3
t_0006d41a73a8     video         bg  000cf7   source      4
t_0006d41a73a8     video         bg  000cf7   source      4
t_0006d41a73a8     video         bg  000cf7   source      4
t_0006d41a73a8     video         bg  000cf7   source      4
t_0006d41a73a8     video         bg  000cf7   source      4
t_4054df11a74e     video         es  6e3ba4   source      2
t_4054df11a74e     html5         en  6e3ba4   source      2

In [43]:
what_are_you= final_test.drop(['kind', 'channel', 'category', 'level', 
                               'parent','language_x','topic_id'], axis=1)
what_are_you

                   content_ids
topic_id
t_00004da3a1b2  c_5bc0e1e2cba0
t_00004da3a1b2  c_376c5a8eb028
t_00004da3a1b2  c_1108dd0c7a5d
t_00004da3a1b2  c_76231f9d0b5e
t_00068291e9a4  c_89ce9367be10
t_00068291e9a4  c_ebb7fdf10a7e
t_00068291e9a4  c_639ea2ef9c95
t_00068291e9a4  c_ac1672cdcd2c
t_00069b63a70a  c_11a1dc0bfb99
t_0006d41a73a8  c_b972646631cb
t_0006d41a73a8  c_5e375cf14c47
t_0006d41a73a8  c_1c57a1316568
t_0006d41a73a8  c_0c6473c3480d
t_0006d41a73a8  c_d7a0d7eaf799
t_4054df11a74e  c_f2d184a98231
t_4054df11a74e  c_3695c5dc1df6

In [44]:
x_raw.isnull().sum()

kind          0
language_x    0
channel       0
category      0
level         0
dtype: int64

In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder, MultiLabelBinarizer

In [46]:
premodel_x= OneHotEncoder(dtype='int')

In [47]:
premodel_y= OneHotEncoder(dtype='int', min_frequency=15)

In [48]:
premodel_yB= OneHotEncoder(dtype='int', max_categories=16)

In [49]:
X=premodel_x.fit_transform(x_raw).toarray()

In [50]:
Y=premodel_y.fit_transform(y_raw).toarray()

In [51]:
YB=premodel_yB.fit_transform(y_raw).toarray()

In [52]:
Y.shape

(279903, 492)

In [53]:
YB.shape

(279903, 16)

In [54]:
premodel_y.get_feature_names_out()

array(['content_ids_c_00d385f8d61a', 'content_ids_c_0137efeb3988',
       'content_ids_c_015a9e386b1f', 'content_ids_c_023462d3331d',
       'content_ids_c_02b72bedbfd5', 'content_ids_c_02b9e9727e23',
       'content_ids_c_02d1ca83ed66', 'content_ids_c_02de0d44e2b8',
       'content_ids_c_03a8f2ae83f6', 'content_ids_c_0496ecbb88c7',
       'content_ids_c_04e6b34426c6', 'content_ids_c_05d32f97e21e',
       'content_ids_c_05ef2b4fab20', 'content_ids_c_05ff276325e3',
       'content_ids_c_07231fd60d79', 'content_ids_c_0754c5747851',
       'content_ids_c_08037a1cab37', 'content_ids_c_085d324f601b',
       'content_ids_c_08a330d17115', 'content_ids_c_08b2070f92e0',
       'content_ids_c_08f8d103a84f', 'content_ids_c_09184d563897',
       'content_ids_c_094b3a5c5071', 'content_ids_c_0aeaa1747295',
       'content_ids_c_0b4243b2198d', 'content_ids_c_0b46a7601ffc',
       'content_ids_c_0df9eb465351', 'content_ids_c_0e2f70bb0d6c',
       'content_ids_c_0e6d22c63a9b', 'content_ids_c_0f5c2fc2edb6',
       'content_ids_c_0f693f41fbc3', 'content_ids_c_10a3d4f103f8',
       'content_ids_c_10dc6bf228db', 'content_ids_c_112c1086f535',
       'content_ids_c_115e616e813a', 'content_ids_c_11bebc650d5c',
       'content_ids_c_12ddbf4ac018', 'content_ids_c_13c5767c1a9c',
       'content_ids_c_14750440cc80', 'content_ids_c_14757b5d634b',
       'content_ids_c_14b23e9bc2e6', 'content_ids_c_15099e81a8e3',
       'content_ids_c_15fafef749e7', 'content_ids_c_163a2248df13',
       'content_ids_c_16e3e3231fa1', 'content_ids_c_18eaf7f1ec43',
       'content_ids_c_198622457139', 'content_ids_c_19da09ae1183',
       'content_ids_c_1a9452757838', 'content_ids_c_1c33e61d171f',
       'content_ids_c_1c9bd6d2b80d', 'content_ids_c_1d3b7bd865ea',
       'content_ids_c_1d7b727c6b7d', 'content_ids_c_1df06d298371',
       'content_ids_c_1e28455f4396', 'content_ids_c_1e6825b0150c',
       'content_ids_c_1ed7715c3a46', 'content_ids_c_1f4597ff621d',
       'content_ids_c_1f4e10888873', 'content_ids_c_2017ce636c72',
       'content_ids_c_2049b296dcb7', 'content_ids_c_20c1d27cc859',
       'content_ids_c_20e447c4074e', 'content_ids_c_2155a93e52a3',
       'content_ids_c_21a241a948d4', 'content_ids_c_222e318d6d8a',
       'content_ids_c_2286f5ae932d', 'content_ids_c_22a2c4a76997',
       'content_ids_c_22fdf779093b', 'content_ids_c_23c98583c28f',
       'content_ids_c_260a94bd6c46', 'content_ids_c_265d0272d28d',
       'content_ids_c_26bc8f378b19', 'content_ids_c_26db0b5ae4d5',
       'content_ids_c_27307a1fe5e2', 'content_ids_c_27463f3daa24',
       'content_ids_c_2756dfda5000', 'content_ids_c_27e0d563dbcd',
       'content_ids_c_27e9adf9b560', 'content_ids_c_28181d600353',
       'content_ids_c_284789b696a2', 'content_ids_c_28a218095c72',
       'content_ids_c_28c98c54a568', 'content_ids_c_2930b1695810',
       'content_ids_c_29633da013a9', 'content_ids_c_29644f6f202c',
       'content_ids_c_2974b2fed327', 'content_ids_c_2acb4a131ff7',
       'content_ids_c_2b2563f2c8df', 'content_ids_c_2b2bd83c3590',
       'content_ids_c_2b4d256e665a', 'content_ids_c_2b56fffddfa1',
       'content_ids_c_2c3fd6d77694', 'content_ids_c_2c7a7be82a9f',
       'content_ids_c_2d06f4693cb1', 'content_ids_c_2ea4cf11d20f',
       'content_ids_c_2f8849826d71', 'content_ids_c_3064bb106bbd',
       'content_ids_c_309867d1b883', 'content_ids_c_311878437dcb',
       'content_ids_c_311a1d74ec50', 'content_ids_c_31f8cb2934f3',
       'content_ids_c_327cebe36ab1', 'content_ids_c_332dbfdfdf48',
       'content_ids_c_3386a0af5cad', 'content_ids_c_3396470c8eb1',
       'content_ids_c_34168e172d52', 'content_ids_c_346ceb3fc7ca',
       'content_ids_c_3508d4650742', 'content_ids_c_35f0c36a3114',
       'content_ids_c_36e2d63da749', 'content_ids_c_37b82c822fef',
       'content_ids_c_3856cf0f321a', 'content_ids_c_3890678b2b34',
       'content_ids_c_389337e1386d', 'content_ids_c_3a12b23519f3',
       'content_ids_c_3a485a35c0d4', 'content_ids_c_3a94b8b50c48',
       'content_ids_c_3aafe3a6a071', 'content_ids_c_3ac64d54be2e',
       'content_ids_c_3ad91580cbb5', 'content_ids_c_3bcc0b986e1b',
       'content_ids_c_3c0f990c53aa', 'content_ids_c_3c20dba79f4b',
       'content_ids_c_3cb779754c7b', 'content_ids_c_3cbc31973b3c',
       'content_ids_c_3d20006cb20b', 'content_ids_c_3d3cc3edb5cd',
       'content_ids_c_3d47e3f1b201', 'content_ids_c_3dd17adb64e6',
       'content_ids_c_3e8eb020fe8f', 'content_ids_c_3ed274c1ca25',
       'content_ids_c_3faa88704d1e', 'content_ids_c_40579c306c94',
       'content_ids_c_414ca206424b', 'content_ids_c_41b8fce506db',
       'content_ids_c_42bab5034fda', 'content_ids_c_4323575ad506',
       'content_ids_c_4378534c9396', 'content_ids_c_439acef137aa',
       'content_ids_c_43b00471a625', 'content_ids_c_43e04e43e5a9',
       'content_ids_c_44aca56f4be6', 'content_ids_c_44ccd51608eb',
       'content_ids_c_454e86124b94', 'content_ids_c_45e9a78607e9',
       'content_ids_c_462c305fe5d3', 'content_ids_c_47755ce04dcc',
       'content_ids_c_4797fda6467a', 'content_ids_c_47b8b96fa47e',
       'content_ids_c_47e3816d74b3', 'content_ids_c_4834c429632d',
       'content_ids_c_484e80aee329', 'content_ids_c_4979670bba39',
       'content_ids_c_498991d55f48', 'content_ids_c_4b4662dd116d',
       'content_ids_c_4baac9a8fc6c', 'content_ids_c_4bd5f2562555',
       'content_ids_c_4c867a47caa1', 'content_ids_c_4ca2414dacbe',
       'content_ids_c_4cb59fef0e36', 'content_ids_c_4d1b3e091a28',
       'content_ids_c_4f5925b37bdf', 'content_ids_c_50513ae53649',
       'content_ids_c_51bc92931b79', 'content_ids_c_51f54c5606a3',
       'content_ids_c_5210b9ed4783', 'content_ids_c_5240c6d3f57b',
       'content_ids_c_52ba67f30e84', 'content_ids_c_532b8744553b',
       'content_ids_c_538dbf499196', 'content_ids_c_540bb23bad75',
       'content_ids_c_54307134fd0e', 'content_ids_c_54a93638d8db',
       'content_ids_c_5555685826c0', 'content_ids_c_55d9ce9fdb18',
       'content_ids_c_566641c5420d', 'content_ids_c_56b61bc6f214',
       'content_ids_c_56dda8e4f6a2', 'content_ids_c_57cd38de5544',
       'content_ids_c_57d5544dba1f', 'content_ids_c_5967fd9beac1',
       'content_ids_c_59778b25b537', 'content_ids_c_59f3c0dfd093',
       'content_ids_c_5a3c3fe31842', 'content_ids_c_5a9537dc032c',
       'content_ids_c_5b4e9a2921df', 'content_ids_c_5c1955b2a8a3',
       'content_ids_c_5c522f58422c', 'content_ids_c_5d0165440173',
       'content_ids_c_5d1cc684158b', 'content_ids_c_5d4c0a90e7f7',
       'content_ids_c_5dad68e318ca', 'content_ids_c_5ddd339d8eb5',
       'content_ids_c_5fa5f01d3c25', 'content_ids_c_602402137003',
       'content_ids_c_6062d2e46506', 'content_ids_c_60afb93bd900',
       'content_ids_c_62d4fa6f12a3', 'content_ids_c_63629624ee82',
       'content_ids_c_63f65fd7a509', 'content_ids_c_64253a13cb35',
       'content_ids_c_64dd312af8c3', 'content_ids_c_666d0be404c3',
       'content_ids_c_6682775cfb9b', 'content_ids_c_66e748649cb3',
       'content_ids_c_68b83740068a', 'content_ids_c_68c33f74debf',
       'content_ids_c_69dfcc6b48a9', 'content_ids_c_6a57605f01ad',
       'content_ids_c_6b0e3788770f', 'content_ids_c_6b9542168065',
       'content_ids_c_6c0475f8a2b4', 'content_ids_c_6c674f8557ac',
       'content_ids_c_6c80790eb291', 'content_ids_c_6c9e02851290',
       'content_ids_c_6d1b3639731e', 'content_ids_c_6d3b0fc13589',
       'content_ids_c_6df2678a672a', 'content_ids_c_6e344e86b0fa',
       'content_ids_c_6e843d69d10e', 'content_ids_c_6edda63a7e93',
       'content_ids_c_7066c9810cdc', 'content_ids_c_713f55bd0312',
       'content_ids_c_71c003a3c17f', 'content_ids_c_71c083ac1adc',
       'content_ids_c_72a88d28ff24', 'content_ids_c_72f59e64fcfa',
       'content_ids_c_741acfff0910', 'content_ids_c_7428f44fc4f4',
       'content_ids_c_742ff4211fce', 'content_ids_c_74d4bec457f8',
       'content_ids_c_755b309ba173', 'content_ids_c_7633cc7bc1de',
       'content_ids_c_76a6cad0a18f', 'content_ids_c_76c116c30df2',
       'content_ids_c_76ea3f6f2dca', 'content_ids_c_78175acae40b',
       'content_ids_c_7868f655c31e', 'content_ids_c_78794e06d8a8',
       'content_ids_c_788ae4a05347', 'content_ids_c_7906e7f7fcd6',
       'content_ids_c_7917b6adfe51', 'content_ids_c_7971ba5f03c4',
       'content_ids_c_7a5cf8d045f2', 'content_ids_c_7b9e08632d00',
       'content_ids_c_7c1d868ba52f', 'content_ids_c_7c95473f0dbb',
       'content_ids_c_7d1d1f15abf2', 'content_ids_c_7da887213a23',
       'content_ids_c_7e9ca0fe81d4', 'content_ids_c_7f22b906034e',
       'content_ids_c_7fe8b62a1c94', 'content_ids_c_801ebb48a5d8',
       'content_ids_c_809c2197827f', 'content_ids_c_8103486cc449',
       'content_ids_c_81d4a1d93f83', 'content_ids_c_82175184bdc3',
       'content_ids_c_82b687237100', 'content_ids_c_833e94c9027a',
       'content_ids_c_834e867a6b6f', 'content_ids_c_841b05d96382',
       'content_ids_c_8453fab783ce', 'content_ids_c_847baa69d7d1',
       'content_ids_c_8482286a1f71', 'content_ids_c_8552d4110c9d',
       'content_ids_c_856c61f85f49', 'content_ids_c_86e4ca3900dd',
       'content_ids_c_88e30ffbc719', 'content_ids_c_890bb425c099',
       'content_ids_c_895e52aa9e0a', 'content_ids_c_89d60a25d3f7',
       'content_ids_c_89d6e0616cde', 'content_ids_c_8a48f2329fc7',
       'content_ids_c_8a52dece74f3', 'content_ids_c_8a97f5856ba5',
       'content_ids_c_8aa34d46e1fb', 'content_ids_c_8ad113a7a801',
       'content_ids_c_8b425f8c3577', 'content_ids_c_8b4557f28b9d',
       'content_ids_c_8b7cb3a4de00', 'content_ids_c_8bbd6bf8b72c',
       'content_ids_c_8c261a66567f', 'content_ids_c_8cb83f24ccc9',
       'content_ids_c_8d58366d230b', 'content_ids_c_8e52edfb5654',
       'content_ids_c_8e557776e57a', 'content_ids_c_8e8da569eaaf',
       'content_ids_c_8ed8ac04408f', 'content_ids_c_8f01d58723cd',
       'content_ids_c_8f16ae0a62b3', 'content_ids_c_8f6be5f4e146',
       'content_ids_c_909e0c45e467', 'content_ids_c_934400809185',
       'content_ids_c_9356bbb229bd', 'content_ids_c_93979a44a571',
       'content_ids_c_93bad4d8dfa7', 'content_ids_c_942b740b2d8c',
       'content_ids_c_945d6fcff46d', 'content_ids_c_9504a78f29a3',
       'content_ids_c_953af6cf14e9', 'content_ids_c_953def0b4d9a',
       'content_ids_c_95f720bba8c3', 'content_ids_c_9671367bdf8a',
       'content_ids_c_96beeb3c9f44', 'content_ids_c_96c0336d7e17',
       'content_ids_c_96dad9a5dffb', 'content_ids_c_96f19cece9d0',
       'content_ids_c_982e77d151b8', 'content_ids_c_9836c2508805',
       'content_ids_c_98735b1546db', 'content_ids_c_9951b18b4ea2',
       'content_ids_c_9985169757ce', 'content_ids_c_99d4981eb97a',
       'content_ids_c_9a519e2fb6dc', 'content_ids_c_9a6f3a122c56',
       'content_ids_c_9b5f3fc76568', 'content_ids_c_9c8925b02d9b',
       'content_ids_c_9d1e255fbc26', 'content_ids_c_9d922a45e16d',
       'content_ids_c_9dbd6a5c0ab5', 'content_ids_c_9e535853b1c5',
       'content_ids_c_9f1ced514fd3', 'content_ids_c_9f4ba7b136af',
       'content_ids_c_9fc1c243f309', 'content_ids_c_a10f16b4d87a',
       'content_ids_c_a14f9f7fc7f1', 'content_ids_c_a1c779c14cbf',
       'content_ids_c_a27ab39f4654', 'content_ids_c_a2d7f3bf94ad',
       'content_ids_c_a349bc7f7734', 'content_ids_c_a38564ea0853',
       'content_ids_c_a39a8828edde', 'content_ids_c_a3c03da4501d',
       'content_ids_c_a41d868a0df3', 'content_ids_c_a5bf7c7ea53c',
       'content_ids_c_a632d9da5307', 'content_ids_c_a7dbac54ebaa',
       'content_ids_c_a8456804432c', 'content_ids_c_a8e91455c958',
       'content_ids_c_a99a9622f854', 'content_ids_c_aa305bf6fdd0',
       'content_ids_c_aae9416da064', 'content_ids_c_ab95a1e95c2f',
       'content_ids_c_ac801a703e39', 'content_ids_c_ac8484961406',
       'content_ids_c_ac92462dfe6d', 'content_ids_c_acf794b2b13f',
       'content_ids_c_adaf482f71e0', 'content_ids_c_ae6d8ac930e9',
       'content_ids_c_af02c8d450c5', 'content_ids_c_afc6b23cc6b4',
       'content_ids_c_b075bfd0cc18', 'content_ids_c_b0f48d6be352',
       'content_ids_c_b166743d72f2', 'content_ids_c_b2c157ac776b',
       'content_ids_c_b31ff2af0347', 'content_ids_c_b42e14c79aad',
       'content_ids_c_b44c206ad756', 'content_ids_c_b45bf67ddfc6',
       'content_ids_c_b51296c608fc', 'content_ids_c_b5ac27676711',
       'content_ids_c_b6819b9c64df', 'content_ids_c_b7ae4bc81236',
       'content_ids_c_b7e19acccb24', 'content_ids_c_ba1ad264c72c',
       'content_ids_c_bbaa540bd99c', 'content_ids_c_bd5af5739f86',
       'content_ids_c_bddb410ec755', 'content_ids_c_be3a38d884b2',
       'content_ids_c_bef43d567e77', 'content_ids_c_bfd4bb44a329',
       'content_ids_c_bffd1c609483', 'content_ids_c_c19e0c488474',
       'content_ids_c_c1f1b6099b3a', 'content_ids_c_c27aea50669a',
       'content_ids_c_c2ee609f8ec7', 'content_ids_c_c34d3bc00052',
       'content_ids_c_c3679fe85363', 'content_ids_c_c37be37c4452',
       'content_ids_c_c4f742b82242', 'content_ids_c_c5c5ee163944',
       'content_ids_c_c61d09a619d4', 'content_ids_c_c63276e3a694',
       'content_ids_c_c65188d842ea', 'content_ids_c_c676c16a5cdc',
       'content_ids_c_c69fc19ab8f2', 'content_ids_c_c838a8accfe5',
       'content_ids_c_c843d1162327', 'content_ids_c_c9a277289cc6',
       'content_ids_c_ca6767301e8b', 'content_ids_c_ca82956ce88e',
       'content_ids_c_cb261bd5542c', 'content_ids_c_cbc99d0397b2',
       'content_ids_c_cbebb2598629', 'content_ids_c_cc630bf8afec',
       'content_ids_c_cf081d33725d', 'content_ids_c_d03e16391c32',
       'content_ids_c_d21214fbf579', 'content_ids_c_d22e17849b79',
       'content_ids_c_d2b3b43d838a', 'content_ids_c_d306e023c753',
       'content_ids_c_d3c5ae854144', 'content_ids_c_d42f89c54fb9',
       'content_ids_c_d43887de7054', 'content_ids_c_d43f99ed5df9',
       'content_ids_c_d682100b25c9', 'content_ids_c_d6c6fba667e4',
       'content_ids_c_d7010c0718e0', 'content_ids_c_d7a46ad2aa96',
       'content_ids_c_d884ab6f1d77', 'content_ids_c_d8bdf053c63a',
       'content_ids_c_d94fa3b7e31d', 'content_ids_c_d9e534fa02a6',
       'content_ids_c_da57e633c9f0', 'content_ids_c_da8ea953a580',
       'content_ids_c_db58f1851553', 'content_ids_c_db7b0985c3df',
       'content_ids_c_dbc352e30342', 'content_ids_c_dcbdcd5246b6',
       'content_ids_c_dce3269cf0e6', 'content_ids_c_dd739e116435',
       'content_ids_c_de5caae54cbb', 'content_ids_c_dea97419ac19',
       'content_ids_c_ded429aabb5b', 'content_ids_c_ded61d6ce1a8',
       'content_ids_c_e072bd058fb9', 'content_ids_c_e1e80c00f399',
       'content_ids_c_e206901b7eaa', 'content_ids_c_e25753013f4c',
       'content_ids_c_e2cd5306b06f', 'content_ids_c_e2e3e8320798',
       'content_ids_c_e3fb0fb30c2b', 'content_ids_c_e416109638d8',
       'content_ids_c_e42f456e72b4', 'content_ids_c_e4b9fd72b153',
       'content_ids_c_e4d7a8797e1e', 'content_ids_c_e5dc09de8e10',
       'content_ids_c_e6db90154404', 'content_ids_c_e6deab18c78a',
       'content_ids_c_e739b04655c6', 'content_ids_c_e861b84b6812',
       'content_ids_c_e8e5520da2af', 'content_ids_c_e8f8569bd811',
       'content_ids_c_ea24b80fc810', 'content_ids_c_ebadd04e6c3b',
       'content_ids_c_ebcb03bff955', 'content_ids_c_ec1b2a9d374b',
       'content_ids_c_ec41e956cb55', 'content_ids_c_ec74a0c65d18',
       'content_ids_c_ee395c66c5a6', 'content_ids_c_eec23d61cb2c',
       'content_ids_c_eff153161446', 'content_ids_c_f0c598e317b7',
       'content_ids_c_f0cb10003a81', 'content_ids_c_f106124090b3',
       'content_ids_c_f1c91f1e6af6', 'content_ids_c_f1facbc3254c',
       'content_ids_c_f1fde7687278', 'content_ids_c_f2eacffb5a1e',
       'content_ids_c_f345f852edf9', 'content_ids_c_f3cf53bfa28a',
       'content_ids_c_f3d7454d3341', 'content_ids_c_f4038503baa6',
       'content_ids_c_f51668fabfba', 'content_ids_c_f533b0890760',
       'content_ids_c_f53b04e17f15', 'content_ids_c_f56f8793d6da',
       'content_ids_c_f5af3dd26d37', 'content_ids_c_f6e713e6e920',
       'content_ids_c_f80e11fb3c41', 'content_ids_c_f81eb8a5eade',
       'content_ids_c_f88b2ff95998', 'content_ids_c_f8cd6001b79d',
       'content_ids_c_f9532f73a39e', 'content_ids_c_f9bb2845f0b4',
       'content_ids_c_fa23df9ef6f5', 'content_ids_c_fa264828a175',
       'content_ids_c_fac4808d4396', 'content_ids_c_fb28bf738d30',
       'content_ids_c_fb90920f1326', 'content_ids_c_fba21849f01e',
       'content_ids_c_fc199fc97963', 'content_ids_c_fc2f00d2f978',
       'content_ids_c_fc67e4c073df', 'content_ids_c_fc81f72acad2',
       'content_ids_c_fc960ebeadd0', 'content_ids_c_fc9ae5357277',
       'content_ids_c_fd34ab8d82f4', 'content_ids_c_fec943ff070d',
       'content_ids_c_ff8a9e08c8f0', 'content_ids_infrequent_sklearn'],
      dtype=object)

In [55]:
premodel_yB.get_feature_names_out()

array(['content_ids_c_00d385f8d61a', 'content_ids_c_04e6b34426c6',
       'content_ids_c_2f8849826d71', 'content_ids_c_3856cf0f321a',
       'content_ids_c_3ed274c1ca25', 'content_ids_c_4f5925b37bdf',
       'content_ids_c_59778b25b537', 'content_ids_c_5a3c3fe31842',
       'content_ids_c_6d3b0fc13589', 'content_ids_c_76ea3f6f2dca',
       'content_ids_c_bfd4bb44a329', 'content_ids_c_d2b3b43d838a',
       'content_ids_c_dd739e116435', 'content_ids_c_e416109638d8',
       'content_ids_c_f1facbc3254c', 'content_ids_infrequent_sklearn'],
      dtype=object)

In [56]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [58]:
XB_train, XB_test, yB_train, yB_test = train_test_split(X, YB, test_size=0.2, random_state=0)

In [59]:
model=DecisionTreeClassifier()

In [60]:
modelB= DecisionTreeClassifier()

In [61]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [62]:
modelB.fit(XB_train, yB_train)

DecisionTreeClassifier()

In [63]:
from sklearn.metrics import accuracy_score

In [64]:
Y_model=model.predict(X_test)

In [65]:
YB_model=modelB.predict(XB_test)

In [66]:
accuracy_score(y_test, Y_model)

0.9637555599221165

In [67]:
accuracy_score(yB_test, YB_model)

0.9977670995516336

In [71]:
X_submt=premodel_x.transform(finalX).toarray()

In [72]:
X_submt.shape

(16, 217)

In [73]:
Y_submt=model.predict(X_submt)

In [74]:
YB_submt=modelB.predict(X_submt)

In [75]:
Y_submt.shape

(16, 492)

In [76]:
YB_submt.shape

(16, 16)

In [84]:
y_submt=pd.DataFrame(Y_submt)
y_submt

,0,1,2,3,4,5,6,7,8,9,...,482,483,484,485,486,487,488,489,490,491
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [78]:
yB_submt=pd.DataFrame(YB_submt)
yB_submt

    0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
0    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
1    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
2    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
3    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
4    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
5    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
6    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
7    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
8    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
9    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
10   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
11   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
12   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
13   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
14   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1
15   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1

In [82]:
sub['content_ids']='c_11a1dc0bfb99'
sub

         topic_id     content_ids
0  t_00004da3a1b2  c_11a1dc0bfb99
1  t_00068291e9a4  c_11a1dc0bfb99
2  t_00069b63a70a  c_11a1dc0bfb99
3  t_0006d41a73a8  c_11a1dc0bfb99
4  t_4054df11a74e  c_11a1dc0bfb99

In [ ]:
sample_submision= sub.to_csv()

In [83]:
Y_model

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])